### ISSUE TITLE
Управление проектом

### ISSUE THREAD

**Issue by Wolwer1nE** [ksevenCh/KalashnikovEstate#4]
Собрать прогресс по проекту: сколько закрыто квадратиков в каждом Issue и написать коммент в этой задаче, тегнув @Wolwer1nE 

- [x] 12 декабря
- [x] 15 декабря
- [x] 19 декабря 
- [x] 22 декабря

Если получилось, то написать 1-2 предложения о том, что получилось.
Если не получилось, то убедиться, что те исполнители, у кого не получилось, написали вопрос кому-то из преподов.

**Comment by Tsaturn** [comment]
@Wolwer1nE
Дизайн - нарисовали в Figma дизайн и прицепили ссылку в Readme

**Comment by Wolwer1nE** [comment]
@Tsaturn 
Открыл заново, мы в этом issuе все этапы пишем.
Еще мне нужны сводки по всем трем направлениям: дизайн+верстка, БД, роутинг+контроллеры. По БД Ксения пришла с вопросом (это хорошо), по контроллерам я не знаю текущий статус.

**Comment by Tsaturn** [comment]
@Wolwer1nE
_Модели_ - написали миграции (создали таблицы в СУБД), создали модели, написали валидации. Рабочая БД готова
_Роутинг и контроллеры_ - прогресса нет, ожидали создание БД 
_Дизайн и вёрстка_ - без изменений, нового прогресса нет. (На данный момент готов дизайн в Figma)

**Comment by Tsaturn** [comment]
@Wolwer1nE
_Модели_ - без изменений (На данный момент есть миграции, модели, валидации. Рабочая БД готова)
_Роутинг и контроллеры_ - появилась вёрстка, в БД записываются данные о пользователе при регистрации, все страницы между собой связаны
_Дизайн и вёрстка_ - без изменений (На данный момент готов дизайн в Figma)

**Comment by Wolwer1nE** [comment]
Надо фронтендеров спасать и деплоить.

**Comment by Tsaturn** [comment]
@Wolwer1nE
Модели - без изменений (Есть миграции, модели, валидации. Рабочая БД готова)
Роутинг и контроллеры - в корзине теперь работает весь функционал (+ Есть вёрстка, в БД записываются данные о пользователе при регистрации, все страницы между собой связаны)
Дизайн и вёрстка -  сделали страницу-каталог, страницу заказа (+ готов дизайн в Figma)
